exclude: ^(docs|studies|tests/samples|src/awkward/_typeparser/generated_parser.py)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.0.0
  hooks:
  - id: setup-cfg-fmt

- repo: https://github.com/asottile/pyupgrade
  rev: "v2.37.3"
  hooks:
  - id: pyupgrade
    args: ["--py36-plus"]

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml]

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear, flake8-print>=5]

- repo: https://github.com/mgedmin/check-manifest
  rev: "0.48"
  hooks:
  - id: check-manifest
    stages: [manual]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    args: ["-L", "ue,subjet,parms,fo,numer,thre"]

- repo: local
  hooks:
  - id: disallow-caps
    name: Disallow improper capitalization
    language: pygrep
    entry: PyBind|Cmake|CCache|Github|PyTest
    exclude: .pre-commit-config.yaml

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: "v0.8.0.4"
  hooks:
  - id: shellcheck
