version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  commands:
    - pip install requests
    - mkdir -p _readthedocs/html
    - dev/download-github-asset scikit-hep/awkward-1.0 docs --dest=_readthedocs/html
