[build-system]
requires = [
    "setuptools>=42.0",
    "wheel>=0.36.0",
    "cmake>=3.13",
    "PyYAML",
]

build-backend = "setuptools.build_meta"


[tool.check-manifest]
ignore = [
    # Hidden files
    ".*",
    ".*/**",
    "**/.*",
    "**/.*/**",

    # Local files
    "docs*/**",
    "dev/**",
    "studies/**",

    "cuda-build.sh",
    "kernel-specification.yml",
    "localbuild.py",

    # Extern files
    "pybind11/*.*",
    "pybind11/pybind11/**",
    "*/example/**",
    "*/doc/**",
    "*/tests/**",
    "*/test/**",
    "*/bin/**",
    "**/Makefile",
    "rapidjson/*.md",
    "rapidjson/docker/*",
    "dlpack/apps/**",
    "dlpack/**/*.md",
    "rapidjson/**/*.json",
    "rapidjson/**/*.yml",
    "rapidjson/**/*.js",
    "rapidjson/**/*.sh",
    "rapidjson/**/*.autopkg",
    "rapidjson/thirdparty/**",
    "rapidjson/docker/**",
]


[tool.cibuildwheel]
test-extras = ["test"]
test-command = "pytest {project}/tests"
skip = ["pp*win*", "pp*-manylinux_i686"]
test-skip = ["*universal2:arm64", "pp*", "*musllinux*"]
manylinux-x86_64-image = "manylinux2014"
build-verbosity = 1

[tool.cibuildwheel.environment]
PIP_ONLY_BINARY = "cmake,numpy"

[[tool.cibuildwheel.overrides]]
select = "cp3?-*"
manylinux-x86_64-image = "manylinux2010"


[tool.pytest.ini_options]
minversion = "6.0"
norecursedirs = ["src", "pybind11", "rapidjson", "studies"]
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = [
  "error",
  "ignore:the imp module is deprecated in favour of importlib:DeprecationWarning",  # move to importlib to fix (setuptools issue)
  "ignore:The NumPy module was reloaded:UserWarning",
]
log_cli_level = "info"
