trigger:
  batch: true
  branches:
    exclude:
      - "*"

pr:
  branches:
    include:
      - "*"

jobs:
  - job: Sphinx

    pool:
      vmImage: "ubuntu-18.04"

    strategy:
      matrix:
        "py38-np*":
          python.version: "3.8"
          python.architecture: "x64"

    steps:
      - checkout: self
        submodules: recursive

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: '$(python.architecture)'
        displayName: 'Python $(python.version)'

      - script: |
          python -m pip install --upgrade pip
        displayName: "Install Pip"

      - script: |
          python -m pip install -r docs-sphinx/requirements.txt
          python -m pip install sphinx_rtd_theme
          sudo apt-get install -y doxygen
        displayName: "Install requirements"

      - script: |
          sphinx-build docs-sphinx/ docs-sphinx/_build/
        displayName: "Generate documentation"

  - job: JupyterBook

    pool:
      vmImage: "ubuntu-18.04"

    strategy:
      matrix:
        "py38-np*":
          python.version: "3.8"
          python.architecture: "x64"

    steps:
      - checkout: self
        submodules: recursive

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: '$(python.architecture)'
        displayName: 'Python $(python.version)'

      - script: |
          python -m pip install --upgrade pip
        displayName: "Install Pip"

      - script: |
          python -m pip install numpy
        displayName: "Install NumPy"

      - script: |
          python -m pip install -U jupyter-book
        displayName: "Install JupyterBook"

      - script: |
          python -m pip install -v .
        displayName: "Build Awkward Array"

      - script: |
          jupyter-book build docs-src
        displayName: "Run notebooks"

      - script: |
          for x in `ls docs-src/_build/html/reports/*.log 2> /dev/null`; do
              echo '===================================================================';
              echo $x;
              echo '===================================================================';
              cat $x;
          done
          [ ! -d "docs-src/_build/html/reports" ]
        displayName: "Check reports"
