name: "Documentation"
description: "Something needs to be explained…"
labels: ["docs"]
assignees: []

body:
  - type: dropdown
    id: where
    attributes:
      label: "Which documentation?"
      description: |
        In the [documentation website](https://awkward-array.org/), the [GitHub README.md](https://github.com/scikit-hep/awkward/blob/main/README.md), [CONTRIBUTING.md](https://github.com/scikit-hep/awkward/blob/main/CONTRIBUTING.md), Python docstrings, or C++ doxygen comments?
      options:
        - Documentation website
        - GitHub README.md
        - CONTRIBUTING.md
        - Python docstrings
        - C++ doxygen comments
        - Other (please explain)?
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: "What needs to be documented?"
      description: |
        If you need to include a screenshot, try **clicking on the rectangle below to highlight it** and then dragging the file in or pasting from the clipboard.
      placeholder: "Tell us what you need to know."
    validations:
      required: true
