name: "Blank issue"
description: "Create a blank issue"
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: "Tell us what's not working."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thank you for submitting an issue; we know that it takes time and effort to do so!

        Note that we'll be closing the issue as soon as a solution is proposed. This is not meant to be unfriendly; it's for our own bookkeeping. If you think the first answer/solution is unsatisfactory, please do continue the thread and we'll reopen it or otherwise address it.
