name: Codecov

on:
  push:
    branches:
      - main
    paths-ignore:
      - README*.md
      - VERSION_INFO
      - .ci/*
      - .readthedocs.yml
      - include/*
      - src/*
      - docs-src/*
      - docs-img/*
      - docs-jupyter/*
      - docs-doxygen/*
      - docs/*
      - studies/*

  workflow_dispatch:

concurrency:
  group: 'coverage-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-20.04

    env:
      PIP_ONLY_BINARY: cmake
      PYTHON_VERSION: "3.10"
      # Ensure predictable hash
      SOURCE_DATE_EPOCH: "1667773939"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: 'Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Install requirements
        run: |
          python3 -m pip install \
            -r requirements-test.txt \
            numpy \
            build

      - name: Prepare generated build sources
        run: |
          python3 dev/generate-kernel-signatures.py
          python3 dev/copy-cpp-headers.py

      - name: Cache awkward-cpp wheel
        id: cache-awkward-cpp-wheel
        uses: actions/cache@v3
        with:
          path: ./awkward-cpp/dist
          key: ${{ github.job }}-${{ matrix.python-version }}-${{ hashFiles('awkward-cpp/**') }}

      - name: Build awkward-cpp wheel
        if: steps.cache-awkward-cpp-wheel.outputs.cache-hit != 'true'
        run: python3 -m build -w ./awkward-cpp

      - name: Install awkward-cpp
        run: python3 -m pip install -v ./awkward-cpp/dist/*.whl

      - name: Build & install awkward
        run: python3 -m pip install -v .

      - name: Print versions
        run: python -m pip list

      - name: Test
        run: >-
          python -m pytest -vv -rs tests --cov=awkward --cov-report=term
          --cov-report=xml

      - name: Upload Codecov results
        uses: codecov/codecov-action@v3
