name: Codecov

on:
  push:
    branches:
      - main
    paths-ignore:
      - README*.md
      - VERSION_INFO
      - .ci/*
      - .readthedocs.yml
      - include/*
      - src/*
      - docs-src/*
      - docs-img/*
      - docs-jupyter/*
      - docs-doxygen/*
      - docs-sphinx/*
      - studies/*

  workflow_dispatch:

concurrency:
  group: 'coverage-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-20.04

    env:
      PIP_ONLY_BINARY: cmake
      PYTHON_VERSION: "3.10"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          # Maybe share these across workflows?
          key: >-
            ${{ github.job }}

      - name: Use ccache
        run: |
          echo "/usr/lib/ccache" >> $GITHUB_PATH
          echo "/usr/local/opt/ccache/libexec" >> $GITHUB_PATH

      - name: 'Python ${{ env.PYTHON_VERSION }}'
        uses: actions/setup-python@v4
        with:
          python-version: '${{ env.PYTHON_VERSION }}'

      - name: Install NumPy
        run: python -m pip install numpy

      - name: Build C++
        run: 'python -m pip install -vv ./awkward-cpp'

      - name: Build Python
        run: 'python -m pip install -v .[test,dev]'

      - name: Print versions
        run: python -m pip list

      - name: Test
        run: >-
          python -m pytest -vv -rs tests --cov=awkward --cov-report=term
          --cov-report=xml

      - name: Upload Codecov results
        uses: codecov/codecov-action@v3
