name: CUDA Kernels Build

on: [push]

jobs:
  setup-cuda-build-process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: '11.5.1'

      - run: python dev/generate-cuda.py && ./cuda-build.sh --install

      - run: python -c "import awkward_cuda_kernels"
