name: CUDA Kernels Build

on: [push]

jobs:
  build-awkward-cuda-kernels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          cuda-version: [11.5, 11.4, 11.3, 11.2, 11.1, 11.0, 10.2]

    steps:
      # - uses: Jimver/cuda-toolkit@v0.2.5
      #   id: cuda-toolkit
      #   with:
      #     cuda: ${{ matrix.cuda-version }}
      # 
      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     miniforge-version: latest

            # - run: conda install -c conda-forge/label/${{ matrix.cuda-conda-label }} cudatoolkit-dev

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - run: python --version

      - run: pip install -r requirements-dev.txt setuptools wheel

      - run: python dev/generate-kernel-signatures.py

      - run: python dev/generate-cuda.py && ./cuda-build.sh ${{ matrix.cuda-version}}

      - uses: actions/upload-artifact@v2
        with:
          path: dist/awkward_cuda_kernels-**-py3-none-**.whl

