name: CUDA Kernels Build

on: [push]

jobs:
  setup-cuda-build-process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: '11.5.1'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - run: python --version

      - run: pip install -r requirements.txt
      - run: pip install -r requirements-test.txt
      - run: pip install -r requirements-dev.txt

      - run: pip install wheel

      - run: python dev/generate-kernel-signatures.py

      - run: python dev/generate-cuda.py && ./cuda-build.sh
