name: CUDA Kernels Build

on: [pull_request]

jobs:
  build-awkward-cuda-kernels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          cuda-version: [11.5.1, 11.4.1, 11.3.1, 11.2.1, 11.1.1, 11.0.3, 10.2]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - run: python --version

      - run: pip install -r requirements-dev.txt setuptools wheel

      - run: python dev/generate-kernel-signatures.py

      - if: ${{ matrix.cuda-version }} == 11.5.1 || ${{ matrix.cuda-version }} == 10.2
        run: |
          pip install pytest
          python dev/generate-cuda.py
          ./cuda-build.sh -c ${{ matrix.cuda-version}} -i
          python -m pytest -vvrs tests-cuda/test_1270-install-test.py

      - if: ${{ matrix.cuda-version }} != 11.5.1 && ${{ matrix.cuda-version }} != 10.2
        run: |
          python dev/generate-cuda.py
          ./cuda-build.sh -c ${{ matrix.cuda-version}}

      - uses: actions/upload-artifact@v2
        with:
          path: dist/awkward_cuda_kernels-*.whl
