name: CUDA Kernels Build

on: [push]

jobs:
  setup-cuda-toolkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: '11.5.1'
      - run: nvcc -V
