name: Deploy

on:
  workflow_dispatch:
  release:
    types:
    - published


jobs:
  build:
    name: "Build wheel & sdist"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Compute SOURCE_DATE_EPOCH
      run: |
        SOURCE_DATE_EPOCH="$(git log -1 --format="%ad" --date=unix -- pyproject.toml)"
        echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH" >> $GITHUB_ENV

    - name: Prepare build files
      run: pipx run nox -s prepare

    - name: Build distributions
      run: pipx run build --sdist --wheel

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        path: |
          dist/*

  upload:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        password: ${{ secrets.pypi_password }}
