name: Wheels

on:
  workflow_dispatch:
  release:
    types:
    - published

env:
  # Ensure predictable hash
  SOURCE_DATE_EPOCH: "1667773939"


jobs:

  make_sdists:
    name: "Make SDists"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare build files
      run: pipx run nox -s prepare

    - name: Build awkward-cpp sdist
      run: pipx run build --sdist awkward-cpp

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        path: |
          dist/*.tar.gz
          awkward-cpp/dist/*.tar.gz


  build_wheels:
    name: "Wheel: ${{ matrix.type }} ${{ matrix.arch }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [auto64]
        build: ["cp*", "pp*"]

        include:
        - os: macos-latest
          type: "Universal"
          arch: universal2
          build: "cp*"

        - os: windows-latest
          arch: auto64
          build: "cp*"

        - os: windows-latest
          arch: auto32
          build: "cp{37,38,39}-*"


    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare build files
      run: pipx run nox -s prepare

    - uses: pypa/cibuildwheel@v2.11.2
      env:
        CIBW_BUILD: ${{ matrix.build }}
        CIBW_ARCHS: ${{ matrix.arch }}
      with:
        config-file: cibuildwheel.toml
        package-dir: awkward-cpp

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl


  build_alt_wheels:
    name: "Wheel: ${{ matrix.python }} on ${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [37, 38, 39, 310, 311]
        arch: [aarch64]
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare build files
      run: pipx run nox -s prepare

    - uses: docker/setup-qemu-action@v2.1.0

    - uses: pypa/cibuildwheel@v2.11.2
      env:
        CIBW_BUILD: cp${{ matrix.python }}-*
        CIBW_ARCHS: ${{ matrix.arch }}
      with:
        config-file: cibuildwheel.toml
        package-dir: awkward-cpp

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl

  upload_all:
    needs: [build_wheels, build_alt_wheels, make_sdist, check_version]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        password: ${{ secrets.pypi_password }}
