name: Docs
on:
  pull_request:

jobs:
  Sphinx:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: docs-${{ github.job }}
    - name: Use ccache
      run: |
        echo "/usr/lib/ccache" >> $GITHUB_PATH
        echo "/usr/local/opt/ccache/libexec" >> $GITHUB_PATH
    - name: Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Pip
      run: python -m pip install --upgrade pip
    - name: Install requirements
      run: |
        python -m pip install -r docs-sphinx/requirements.txt
        sudo apt-get install -y doxygen
    - name: Build Awkward Array
      run: python -m pip install -v .
    - name: Generate documentation
      run: sphinx-build docs-sphinx/ docs-sphinx/_build/
    - uses: actions/upload-artifact@v3
      with:
        name: jupyter-cache
        path: docs-sphinx/.jupyter_cache
    # - name: Trigger RTD Build
      # # NB: head_ref is only valid for PR triggers
      # run: curl -X POST -d "branches=${{ github.head_ref }}" -d "token=${{ secrets.RTD_WEBHOOK_TOKEN }}" "${{ secrets.RTD_WEBHOOK_URL }}"
