name: Docs
on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [released]
  workflow_dispatch:

concurrency:
  group: 'docs-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.10.6"

jobs:
  awkward-cpp-wasm:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ env.PYTHON_VERSION }}"

    - name: Prepare build files
      run: |
        python3 -m pip install pyyaml
        python3 dev/generate-kernel-signatures.py
        python3 dev/copy-cpp-headers.py

    - name: Cache wheel
      id: cache-awkward-cpp-wasm-wheel
      uses: actions/cache@v3
      with:
        path: ./awkward-cpp/dist
        key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-awkward-cpp-wasm-${{ hashFiles('awkward-cpp/**') }}

    - name: Install EMSDK
      uses: mymindstorm/setup-emsdk@v11
      if: steps.cache-awkward-cpp-wasm-wheel.outputs.cache-hit != 'true'
      with:
        version: 3.1.14

    - name: Build wheel
      if: steps.cache-awkward-cpp-wasm-wheel.outputs.cache-hit != 'true'
      run: |
        # pyodide-build doesn't work out of the box with pipx
        python3 -m pip install pyyaml pyodide-build==0.21.0
        export CMAKE_ARGS="-DEMSCRIPTEN=1"
        pyodide build --exports whole_archive
      working-directory: awkward-cpp

    - name: Upload wheel
      uses: actions/upload-artifact@v3
      with:
        name: awkward-cpp-wasm
        path: awkward-cpp/dist/awkward*wasm32.whl

  awkward-cpp-x86-64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

      # TODO: remove this once mamba-org/mamba#1726 is fixed
      #       and replace with `-r requirements.txt` in a
      #       non-template `environment.yml`
    - name: Template environment.yml
      run: pipx run --spec cogapp cog -o environment.yml environment.yml.cog
      working-directory: docs-sphinx

      # Technically this give us an environment that is incompatible with
      # the wheel built in the awkward-x86-64 job if the environments
      # solve with different external library versions. By default,
      # ROOT uses cxx-compiler too, so hopefully this won't be an issue
    - name: Setup Python via Conda
      uses: mamba-org/provision-with-micromamba@main
      with:
        # Cache invalidates daily by default
        cache-env: true
        environment-file: docs-sphinx/environment.yml
        extra-specs: |
           python=${{ env.PYTHON_VERSION }}
           doxygen
           pyyaml
           build

    - name: Prepare build files
      run: |
        python3 dev/generate-kernel-signatures.py
        python3 dev/copy-cpp-headers.py

    - name: Cache wheel
      id: cache-awkward-cpp-x86-64-wheel
      uses: actions/cache@v3
      with:
        path: ./awkward-cpp/dist
        key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-awkward-x86-64-wasm-${{ hashFiles('awkward-cpp/**') }}

    - name: Build wheel
      if: steps.cache-awkward-cpp-x86-64-wheel.outputs.cache-hit != 'true'
      run: python3 -m build -w ./awkward-cpp

    - name: Upload wheel
      uses: actions/upload-artifact@v3
      with:
        name: awkward-cpp-x86-64
        path: awkward-cpp/dist/awkward*.whl

  awkward:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build wheel
      run: pipx run build -w

    - name: Upload wheel
      uses: actions/upload-artifact@v3
      with:
        name: awkward
        path: dist/awkward*.whl

  build-docs:
    runs-on: ubuntu-22.04
    needs: [awkward-cpp-wasm, awkward-cpp-x86-64, awkward]
    defaults:
      run:
        # Ensure conda env is activated
        shell: "bash -l {0}"
    steps:
    - uses: actions/checkout@v3

      # TODO: remove this once mamba-org/mamba#1726 is fixed
      #       and replace with `-r requirements.txt` in a
      #       non-template `environment.yml`
    - name: Template environment.yml
      run: pipx run --spec cogapp cog -o environment.yml environment.yml.cog
      working-directory: docs-sphinx

      # Technically this give us an environment that is incompatible with
      # the wheel built in the awkward-x86-64 job if the environments
      # solve with different external library versions. By default,
      # ROOT uses cxx-compiler too, so hopefully this won't be an issue
    - name: Setup Python via Conda
      uses: mamba-org/provision-with-micromamba@main
      with:
        # Cache invalidates daily by default
        cache-env: true
        environment-file: docs-sphinx/environment.yml
        extra-specs: |
           python=${{ env.PYTHON_VERSION }}
           doxygen

    - name: Build awkward wheel
      run: pipx run build -w

    - name: Copy awkward wheel to JupyterLite
      run: |
        mkdir -p docs-sphinx/lite/pypi/
        cp dist/awkward*.whl docs-sphinx/lite/pypi/

    - name: Download awkward-cpp WASM wheel
      uses: actions/download-artifact@v3
      with:
        name: awkward-cpp-wasm
        path: docs-sphinx/lite/pypi

    - name: Download awkward-cpp x86_64 wheel
      uses: actions/download-artifact@v3
      with:
        name: awkward-cpp-x86-64
        path: dist

    - name: Install awkward wheel
      run: python3 -m pip install dist/awkward*.whl

    - name: Generate documentation
      run: sphinx-build -M html . _build/
      working-directory: docs-sphinx

    - name: Upload documentation
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: docs-sphinx/_build/html

    - name: Upload Jupyter Book cache
      uses: actions/upload-artifact@v3
      with:
        name: jupyter-cache
        path: docs-sphinx/_build/.jupyter_cache

  deploy-docs:
    runs-on: ubuntu-22.04
    needs: [build-docs]
    # We can only deploy for PRs on host repo, or pushes to main
    if: ${{ !(github.event_name == 'pull_request' && (github.event.pull_request.head.repo.full_name != github.repository)) }}
    steps:
    - uses: actions/checkout@v3

    - name: Activate RTD version
      run: |
        # Sanitise ref name
        # NB: head_ref is only valid for PR triggers
        export VERSION_SLUG=$(echo "${{ github.head_ref || github.ref_name }}" | sed -E "s@[_/]@-@")
        # Export for subsequent steps
        echo "VERSION_SLUG=$VERSION_SLUG" >> $GITHUB_ENV
        # Activate version
        curl \
          -X PATCH \
          -H "Authorization: Token ${{ secrets.RTD_TOKEN }}" \
              "https://readthedocs.org/api/v3/projects/awkward-array/versions/$VERSION_SLUG/" \
          -H "Content-Type: application/json" \
          -d '{"active":true,"hidden":true}'

    - name: Trigger RTD build
      run: |
        # Trigger build
        curl \
          -X POST \
          -H "Authorization: Token ${{ secrets.RTD_TOKEN }}" \
              "https://readthedocs.org/api/v3/projects/awkward-array/versions/$VERSION_SLUG/builds/"

    - name: Edit PR description
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
            const script = require('./dev/docs-edit-message.js');
            console.log(script(github, context, "${{ env.VERSION_SLUG }}"));
