name: Packaging Tests

on:
  pull_request:
  workflow_dispatch:


concurrency:
  group: packaging-test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  SOURCE_DATE_EPOCH: "1668811211"

jobs:
  make_sdists:
    name: "Make SDists"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare build files
      run: pipx run nox -s prepare

    - name: Build awkward SDist
      run: pipx run build --sdist

    - name: Build awkward-cpp SDist
      run: pipx run build --sdist awkward-cpp

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        path: |
          dist/*.tar.gz
          awkward-cpp/dist/*.tar.gz


  build_wheels:
    name: "Make Wheel: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare build files
      run: pipx run nox -s prepare

    - uses: pypa/cibuildwheel@v2.12.3
      env:
        CIBW_ARCHS_MACOS: universal2
        CIBW_BUILD: cp39-win_amd64 cp37-manylinux_x86_64 cp38-macosx_universal2
      with:
        config-file: cibuildwheel.toml
        package-dir: awkward-cpp

    - uses: pypa/cibuildwheel@v2.12.3
      if: matrix.os == 'ubuntu-latest'
      env:
        CIBW_BUILD: cp311-manylinux_x86_64
      with:
        config-file: cibuildwheel.toml
        package-dir: awkward-cpp

    - name: Build awkward wheel
      run: pipx run build --wheel .

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: |
          wheelhouse/*.whl
          dist/*.whl
