name: Deploy

on:
  workflow_dispatch:
    inputs:
        version:
            type: string
            description: New version

jobs:
  validate-version:
    name: Validate version string
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Check version
        run: |
          import packaging.version
          packaging.version.parse("${{ inputs.version }}")
        shell: python

  set-pyproject-version:
    name: "Set pyproject version"
    runs-on: ubuntu-latest
    needs: [validate-version]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Check awkward-cpp version matches requirement
        run: |
           sed -E r"s/^version\s*=\s*[\"'](.*)[\"']\s*$/version = \"${{ inputs.version }}\"/"

  set-docs-version:
    name: "Set docs version"
    runs-on: ubuntu-latest
    needs: [validate-version]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Check version
        run: |
          import json
          with open("docs/switcher.json") as f:
            data = json.load(f)
          data.append({
              "version": "${{  }}",
              "url": "https://awkward-array.org/2.0/"
          })
          with open("docs/switcher.json", "w") as f:
            json.dump(data, f)
        shell: python
